### ISSUE TITLE
problem in different wasm-bindgen version

### ISSUE THREAD

**Issue by mirsella** [aecsocket/aeronet#22]
hello !

running `cargo run --example websocket_client -F client --target wasm32-unknown-unknown`:
```
Error:

it looks like the Rust project used to create this Wasm file was linked against
version of wasm-bindgen that uses a different bindgen format than this binary:

  rust Wasm file schema version: 0.2.97
     this binary schema version: 0.2.99

Currently the bindgen format is unstable enough that these two schema versions
must exactly match. You can accomplish this by either updating this binary or
the wasm-bindgen dependency in the Rust project.

You should be able to update the wasm-bindgen dependency with:

    cargo update -p wasm-bindgen --precise 0.2.99

don't forget to recompile your Wasm file! Alternatively, you can update the
binary with:

    cargo install -f wasm-bindgen-cli --version 0.2.97

if this warning fails to go away though and you're not sure what to do feel free
to open an issue at https://github.com/rustwasm/wasm-bindgen/issues!
```
trying `    cargo update -p wasm-bindgen --precise 0.2.99`:
```
error: failed to select a version for the requirement `wasm-bindgen = "=0.2.97"`
candidate versions found which didn't match: 0.2.99
location searched: crates.io index
required by package `js-sys v0.3.74`
    ... which satisfies dependency `js-sys = "^0.3.70"` (locked to 0.3.74) of package `aeronet_websocket v0.11.0 (/home/mirsella/dev/aeronet/crates/aeronet_websocket)`
    ```
    
thanks !

**Comment by mirsella** [comment]
same for the webtransport example

**Comment by aecsocket** [comment]
Hi, I'm on holiday right now, so sorry for the late reply!

From what I understand, this issue happens if `wasm-server-runner`'s `wasm-bindgen` version is different to the version used by the `aeronet` example crate that it tries to run. Currently, we depend on at least 0.2.93, and it looks like you're compiling with 0.2.97, but the server runner is compiled with 0.2.99 (or this might be the other way around, I don't exactly understand the message).

I'll bump the wasm-bindgen dependency to 0.2.99, but unfortunately I'm not sure of a way to ensure that this stays up to date with the server runner binary as well. And I don't think this is testable in CI, because it depends on what version of wasm-server-runner *you* have locally on your machine (which depends on *when* you installed the binary).

**Comment by mirsella** [comment]
hm yeah annoying issue, thanks for the update ! ill test
