### ISSUE TITLE
wasm websocket client can't connect

### ISSUE THREAD

**Issue by mirsella** [aecsocket/aeronet#24]
hello !

ran `cargo run --example websocket_echo_server -F server` and `cargo run --example websocket_client -F client --target wasm32-unknown-unknown`, tested on both chromium and firefox.

on the client, i first click "connect" with the default ip placeholder (`wss://[::1]:25566`) which print in the server console:
```
2024-12-16T16:21:23.117117Z  INFO websocket_echo_server: 14v1 connecting to 13v1
2024-12-16T16:21:23.127036Z  WARN websocket_echo_server: 14v1 disconnected from 13v1 due to error: failed to perform TLS handshake: received fatal alert: CertificateUnknown
```
so i tried with ws instead of wss `ws://localhost:25566`:
```
2024-12-16T16:21:36.308467Z  INFO websocket_echo_server: 14v2 connecting to 13v1
2024-12-16T16:21:36.308722Z  WARN websocket_echo_server: 14v2 disconnected from 13v1 due to error: failed to perform TLS handshake: received corrupt message of type InvalidContentType
```

the browser console:
![image](https://github.com/user-attachments/assets/25c412ef-6d17-4a2f-a34c-0db6323149a3)

with webtransport i couldn't connect either, but its because i couldn't paste the server certificate hash into bevy_egui (seems it doesn't support clipboard).

thanks !

**Comment by aecsocket** [comment]
Hmm, this is kind of a tricky situation. Fundamentally, the problem is that the example demonstrates how to set up a secure web socket server and client, however for this to work you need some certificate which is *not* accepted by the WASM client (since it's self signed). There's two options here:
- the example demonstrates using a secure server, which won't work on WASM client because the certificate isn't recognised by the browser, but this shows best practices when using the server
- the example demonstrates using an insecure client and server, which would work on all platforms without extra setup, but is not best practice since the connection isn't encrypted.

Note that, if the server is set up with encryption, trying to connect to it with `ws` won't work, since the server expects encryption but the client gives it something completely different.

I'm not really sure what approach to go with here.

Also, the clipboard pasting issue is different and is due to egui or bevy_egui? not supporting pasting for some reason. You can work around it by clicking into the text box, clicking out of the bevy content, then pressing ctrl+v, and it should paste it in. I thought I put this in the instructions somewhere, but maybe not. I'll update it.

**Comment by mirsella** [comment]
i think having the example be a correct secure server is the right thing, even if it need more commands to run it. the command can just be put before the cargo run wasm client in the readme no big deal i think ?
or maybe the server when starting write its certificate to a file, that is included in the client library ? i dont know if its a good idea

**Comment by mirsella** [comment]
question, to use [with_native_certs](https://docs.rs/aeronet_websocket/latest/aeronet_websocket/client/struct.ClientConfigBuilder.html#method.with_native_certs) the server need to be behind a reverse proxy like nginx that handle the certificates ?

**Comment by aecsocket** [comment]
> i think having the example be a correct secure server is the right thing, even if it need more commands to run it. the command can just be put before the cargo run wasm client in the readme no big deal i think ? or maybe the server when starting write its certificate to a file, that is included in the client library ? i dont know if its a good idea, im new to "low" level networking you'd have to use with_tls_config right ? sorry im not very useful lol, but i think having the example works are definitely important ! especially for something harder like websocket and webtransport on wasm !
> 
> thanks !

It's more complicated than just a command before running the client. The problem is that the WASM client, if using `wss`, will reject any certificate which isn't signed (possibly transitively) by a CA on your machine. On WebTransport, we have a way out via `serverCertificateHashes`, which lets you give cert hashes to ignore. But on WebSocket, we don't have an escape hatch like this. So even if the server generated self-signed certificates and output the hash somewhere, the client wouldn't be able to do anything with it. On WASM WebSocket, we can't *do* anything with that certificate, to let the browser accept it.

Yes, having the example work is important (that's the whole point of an example lol), but we're still back to the original issue of either:
- works (encrypted) on native, breaks on WASM
- works (unencrypted) on native, works (unencrypted) on WASM

Personally, I'd rather take option 1, since it's more comprehensive code-wise (shows you how `Identity` works).

> question, to use [with_native_certs](https://docs.rs/aeronet_websocket/latest/aeronet_websocket/client/struct.ClientConfigBuilder.html#method.with_native_certs) the server need to be behind a reverse proxy like nginx that handle the certificates ? or the aeronet server should handle the certificates itself ?

The server should handle certificates by itself. It uses `rustls::ServerConfig` to handle all of the crypto, so you don't need to put it behind a reverse proxy. Just give it your valid certificates.

**Comment by mirsella** [comment]
alright then, thanks for the explanation !

**Comment by mirsella** [comment]
maybe a little comment on the list of example, for web transport that you need to copy the cert (with the workaround to paste) and for web socket that it doesn't actually work since it needs real certificates

**Comment by aecsocket** [comment]
Good shout, I'll update the docs to make this clearer. Where do you think would have the most visibility for people trying the examples?

**Comment by mirsella** [comment]
well directly on the readme no ? on each example part:
![Screenshot_20241221-092025_Iceraven](https://github.com/user-attachments/assets/91121463-f312-474e-9788-76f05b9a6603)
